// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSkfMhW4PRh31fRCVDOehXpS-T1oXqNxw',
    appId: '1:640893556568:android:3965b0e89f4b520446b72d',
    messagingSenderId: '640893556568',
    projectId: 'applicationhiit',
    storageBucket: 'applicationhiit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8NmydiRw8fEEPWqW2wfeBXtJSgn-avyo',
    appId: '1:640893556568:ios:2dbb449416c1752746b72d',
    messagingSenderId: '640893556568',
    projectId: 'applicationhiit',
    storageBucket: 'applicationhiit.appspot.com',
    androidClientId: '640893556568-5pu5u8funuma2vhiptrp99em8totso57.apps.googleusercontent.com',
    iosClientId: '640893556568-d10i8v46dvq21qhihtvvn5s6d38f6d7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationhiit',
  );
}
